// Code generated by "stringer -type=hubCoil"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[hubHeartbeat-0]
	_ = x[hubActive-1]
	_ = x[hubCoilCount-2]
}

const _hubCoil_name = "hubHeartbeathubActivehubCoilCount"

var _hubCoil_index = [...]uint8{0, 12, 21, 33}

func (i hubCoil) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_hubCoil_index)-1 {
		return "hubCoil(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _hubCoil_name[_hubCoil_index[idx]:_hubCoil_index[idx+1]]
}
