// Code generated by "stringer -type=hubRegister"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[hubIoConnection-0]
	_ = x[hubLightRed-1]
	_ = x[hubLightGreen-2]
	_ = x[hubLightBlue-3]
	_ = x[hubCount-4]
	_ = x[hubRegisterCount-5]
}

const _hubRegister_name = "hubIoConnectionhubLightRedhubLightGreenhubLightBluehubCounthubRegisterCount"

var _hubRegister_index = [...]uint8{0, 15, 26, 39, 51, 59, 75}

func (i hubRegister) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_hubRegister_index)-1 {
		return "hubRegister(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _hubRegister_name[_hubRegister_index[idx]:_hubRegister_index[idx+1]]
}
