// Code generated by "stringer -type=LedAnimation"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnimationRgbControl-0]
	_ = x[AnimationBluePurpleFading-1]
	_ = x[AnimationRedSolid-2]
	_ = x[AnimationBlueSolid-3]
	_ = x[AnimationRedPulsing-4]
	_ = x[AnimationBluePulsing-5]
	_ = x[AnimationRedChasers-6]
	_ = x[AnimationBlueChasers-7]
}

const _LedAnimation_name = "AnimationRgbControlAnimationBluePurpleFadingAnimationRedSolidAnimationBlueSolidAnimationRedPulsingAnimationBluePulsingAnimationRedChasersAnimationBlueChasers"

var _LedAnimation_index = [...]uint8{0, 19, 44, 61, 79, 98, 118, 137, 157}

func (i LedAnimation) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LedAnimation_index)-1 {
		return "LedAnimation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LedAnimation_name[_LedAnimation_index[idx]:_LedAnimation_index[idx+1]]
}
